name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Hangi branch'teki değişikliklerde deploy yapılacaksa belirtin

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Projenizin Node.js sürümünü burada belirtin

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate with Firebase
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase-credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=firebase-credentials.json

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting
