name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Hangi branch'teki değişikliklerde deploy yapılacaksa onu belirtin

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Projenizin Node.js sürümünü burada belirtin

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        echo $FIREBASE_SERVICE_ACCOUNT > firebase-credentials.json
        firebase use --add --project $(jq -r '.project_id' firebase-credentials.json)
        firebase deploy --only hosting --token $(cat firebase-credentials.json | jq -r '.private_key' | firebase login:ci)
